services:
  web:
    build: ./Web
    image: 63070138/img_frontend:lastest
    ports:
      - "8081:80"
    container_name: frontend
  server:
    build: ./Server
    image: 63070138/img_backend:lastest
    ports:
      - "8082:80"
    container_name: backend
